# =============================================================================
# GitHub Secret Scanning Configuration - Order Service
# =============================================================================
# This file configures which paths and patterns should be excluded from
# GitHub's secret scanning to avoid false positives on sample/test data.

# Paths to exclude from secret scanning
paths-ignore:
  # Database sample/seed data - contains mock order and transaction data
  - 'database/data/**'
  - 'database/migrations/**'
  - 'database/seeds/**'

  # Test fixtures and mock data
  - 'OrderService.Tests/**'
  - 'tests/**'
  - 'test-data/**'

  # Documentation and examples
  - 'docs/**'
  - 'examples/**'
  - '*.md'
  - '**/*.md'

  # Build artifacts and dependencies
  - 'bin/**'
  - 'obj/**'
  - 'packages/**'
  - '*.log'
  - 'logs/**'

  # Configuration templates and examples
  - '*.example'
  - '**/*.example'
  - 'appsettings.example.json'
  - 'config/examples/**'

# File patterns to exclude
patterns-ignore:
  # Sample/test configuration files
  - '*.sample.*'
  - '*.template.*'
  - '*.example.*'

  # Test and mock files
  - '*.test.*'
  - '*.spec.*'
  - '*.mock.*'
  - '**/test-*'
  - '**/mock-*'
  - 'Test*'
  - '*Test*'

  # Documentation files
  - 'README*'
  - 'CHANGELOG*'
  - 'LICENSE*'
  - 'CONTRIBUTING*'
  - 'CODE_OF_CONDUCT*'
  - 'PULL_REQUEST_TEMPLATE*'

# Additional exclusions for .NET order service
file-types-ignore:
  # C# test files and projects
  - '**/*.Tests/**'
  - 'tests/**/*.cs'
  - '**/*Test*.cs'
  - '**/*Tests.cs'

  # JSON files in data directories (sample orders, customer data)
  - 'database/**/*.json'
  - 'data/**/*.json'
  - 'fixtures/**/*.json'
  - 'test-data/**/*.json'

  # SQL files with sample data
  - 'database/**/*.sql'
  - 'migrations/**/*.sql'
  - 'seeds/**/*.sql'

  # .NET configuration and project files
  - '**/*.csproj'
  - '**/*.sln'
  - 'appsettings.Development.json'
  - 'appsettings.Test.json'

  # Package and build files
  - 'packages.config'
  - '**/*.nuspec'
