services:
  postgres:
    image: postgres:latest
    container_name: order-postgres-docker
    restart: unless-stopped
    environment:
      POSTGRES_DB: OrderServiceDb_Dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_dev_pass_123
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d OrderServiceDb_Dev']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - aioutlet-network

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service-docker
    restart: unless-stopped
    ports:
      - '3005:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=OrderServiceDb_Dev;Username=postgres;Password=postgres_dev_pass_123;Port=5432
      - RabbitMQ__ConnectionString=amqp://admin:admin123@aioutlet-rabbitmq:5672/
      - JWT__Secret=order_service_jwt_dev_secret_123
      - JWT__Issuer=aioutlet-auth-service
      - JWT__Audience=aioutlet-order-service
      - ServiceDiscovery__UserServiceUrl=http://user-service-docker:80
      - ServiceDiscovery__PaymentServiceUrl=http://payment-service-docker:80
      - ServiceDiscovery__InventoryServiceUrl=http://inventory-service-docker:8080
      - ServiceDiscovery__NotificationServiceUrl=http://notification-service-docker:3008
      - Redis__ConnectionString=aioutlet-redis:6379
      - Redis__Password=redis_dev_pass_123
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - aioutlet-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local

networks:
  aioutlet-network:
    external: true
    name: aioutlet-network
